### ISSUE TITLE
ListPage functionality

### ISSUE THREAD

**Issue by ellengao** [defrancisco/My-Digital-Safe#13]
### TO DO

- [x] Define JSON model to be passed between frontend and backend

- [x] Show list of available notes

- [x] Retrieve and open note on tap

- [ ] Delete note functionality by holding (add confirmation message)

**Comment by defrancisco** [comment]
In the script section of the ListPage.html in the assets folder is a comment including an example of the JSON array of objects returned.

**Comment by defrancisco** [comment]
Example of JSON structure passed from back to front-end.
[
    {"_id":1,"access_date":"2018-13-12 09:13:43","data":"value of note 1","file_name":"note 1"},
    {"_id":2,"access_date":"2018-17-12 09:17:51","data":"Note 2 value look at me I\u0027m a value.","file_name":"note 2"},
    {"_id":3,"access_date":"2018-18-12 09:18:45","data":"test","file_name":"note 3"}
]

**Comment by defrancisco** [comment]
Back-end passes the following to front-end to allow the data model to by dymanic without changes to JS. The keys in the following object are fixed and the values are dynamic. The values represent the keys used in the actual data passed by the back-end.

{
    "id":"id",
    "name":"file_name",
    "date":"access_date"
}
